### ISSUE TITLE
Use the Dedicated server Steam App instead of downloading whole game.

### ISSUE THREAD

**Issue by NolanSyKinsley** [ArghArgh200/SEDS-Setup#12]
There is a space engineers dedicated server App on steam now so you can directly download it instead of downloading the whole game and extracting the dedicated server files. The appid is 298740, here is the reference on steamdb https://steamdb.info/app/298740/

**Comment by phit** [comment]
just submitted a fix for that #13

**Comment by spannerman79** [comment]
This was merged so you can close this @NolanSyKinsley
