### ISSUE TITLE
Possible trick for VRAM ?

### ISSUE THREAD

**Issue by H4Mm3r** [ArghArgh200/SEDS-Setup#20]
Hi there,

Is it possible SE Server is only using VRAM ?

I get a  "System.OutOfMemoryException" on a 8GB RAM dedicated Debian server. As it's a dedicated server, it has no GC, so not much VRAM... Is there any trick to use the 8GB RAM ?

Good works for the script.

Thanks

**Comment by mccorkle** [comment]
Doesn't wine only support 32bit?   IIRC, that limits us to the 4gb range.

::Mark

**Comment by H4Mm3r** [comment]
Wine is 32bit yes, I would be happy to use 4GB instead of the 128MB of the Intel Integrated GC...

Before snapshot.: GC Memory: 516,243,108 B
2016-01-24 17:45:02.936 - Thread:   1 ->     Exception occured: System.OutOfMemoryException: Exception of type 'System.OutOfMemoryException' was thrown.

**Comment by ArghArgh200** [comment]
Not within scope of project. Open this issue with Keen.
