### ISSUE TITLE
Cannot start new world - scenario not found (null)/(null)

### ISSUE THREAD

**Issue by jackthesmack** [ArghArgh200/SEDS-Setup#6]
I get this error when I try starting the server. Here is the log.

>jack@ubuntuServer:~$ cd spaceengineers;./start.sh;screen -x spaceengineers
>spaceengineers is not running, starting
>  inflating: DedicatedServer/steamclient64.dll
>  inflating: DedicatedServer/SteamSDK.dll
>  inflating: DedicatedServer/steam_api.dll
>  inflating: DedicatedServer/steam_api64.dll
> extracting: DedicatedServer/steam_appid.txt
>  inflating: DedicatedServer/tier0_s.dll
>  inflating: DedicatedServer/tier0_s64.dll
>  inflating: DedicatedServer/VRage.Audio.dll
>  inflating: DedicatedServer/VRage.Dedicated.dll
>  inflating: DedicatedServer/VRage.dll
>  inflating: DedicatedServer/VRage.Game.dll
>  inflating: DedicatedServer/VRage.Game.xml
>  inflating: DedicatedServer/VRage.Game.XmlSerializers.dll
>  inflating: DedicatedServer/VRage.Input.dll
>  inflating: DedicatedServer/VRage.Library.dll
>  inflating: DedicatedServer/VRage.Library.xml
>  inflating: DedicatedServer/VRage.Math.dll
>  inflating: DedicatedServer/VRage.Math.xml
>  inflating: DedicatedServer/VRage.Native.dll
>  inflating: DedicatedServer/VRage.Render.dll
>  inflating: DedicatedServer/VRage.xml
>  inflating: DedicatedServer/vstdlib_s.dll
>  inflating: DedicatedServer/vstdlib_s64.dll
>Cleaning world of dead NPC entries - Credits to Andy_S of #space-engineers
>Traceback (most recent call last):
>  File "../../worldcleaner.py", line 17, in <module>
>    origfile = open('Sandbox.sbc').read()
>IOError: [Errno 2] No such file or directory: 'Sandbox.sbc'
>Space Engineers  01_089_015
>Is official: True [NO]
>Environment.Is64BitProcess: False
>2015-07-06 01:00:21.860: Bind IP : 0.0.0.0:27016
>Setting breakpad minidump AppID = 244850
>2015-07-06 01:00:23.833: Server successfully started
>2015-07-06 01:00:23.833: Product name: Space Engineers
>2015-07-06 01:00:23.833: Desc: Space Engineers
>2015-07-06 01:00:23.833: Public IP: (redacted)
>2015-07-06 01:00:23.833: Steam ID: 90096280137716744
>2015-07-06 01:00:24.148: Cannot start new world - scenario not found (null)/(null)
>2015-07-06 01:00:24.463: Server connected to Steam
>2015-07-06 01:00:24.463: Server PolicyResponse (1)

**Comment by ArghArgh200** [comment]
Looks like your world is missing or damaged.

**Comment by jackthesmack** [comment]
I'm starting a new world.

**Comment by ArghArgh200** [comment]
Yeah, for some reason you have to generate the world on your client and upload it.

**Comment by ArghArgh200** [comment]
...Your log also isn't showing the unpacking of any assets or data files. Make sure you're downloading the whole archive with SteamCMD as well as if you're using putty screen kinda wipes your scrollback, so just run ./start.sh start and post that log to see if there's any other stuff that's broken.

**Comment by jackthesmack** [comment]
Ah OK, I made the map on my computer and it worked! Thanks.
