### ISSUE TITLE
spaceengineers is not running, starting

### ISSUE THREAD

**Issue by Pommes9485** [ArghArgh200/SEDS-Setup#7]
I get the following message after executing start.sh:
spaceengineers is not running, starting

After this the programm exits automatically.

I am running Minimalistic Ubuntu.

**Comment by jackthesmack** [comment]
Did you execute ```screen -x spaceengineers```?

**Comment by ArghArgh200** [comment]
Yeah, it starts it in a screen session. I should probably have more clear instructions at runtime for that kinda thing.

Run `screen -ls` to check if you've started it multiple times, and `screen -x spaceengineers` to reattach to the console.

**Comment by avail** [comment]
control + a, d exits the screen without shutting it down (control+c shuts it down)
